name: test download artifact

on: push

jobs:
  Test:
    name: Testing articat 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v5
      with:
       artifact-ids: sha256:fc1e1d57f8c8a8cbee083f15e883e28916a79f06dd80cdb85dd5aed0b9e704e5
    - name: Display structure of downloaded files
      run: ls -R
